name: Terraform

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    terraform_fmt:
        name: Running terraform fmt
        runs-on: ubuntu-latest
        env:
            TF_IN_AUTOMATION: true

        steps:
        - uses: actions/checkout@v2

        - uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 0.13.2

        - name: Running terraform fmt
          run: terraform fmt -check -recursive -diff

    terraform_validate:
      name: Running terraform validate
      runs-on: ubuntu-latest
      env:
          TF_IN_AUTOMATION: true

      steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2

      - name: Running terraform validate
        run: |
            terraform init -backend=false
            terraform validate
    tflint:
        name: Running tflint
        runs-on: ubuntu-latest
        env:
            TF_IN_AUTOMATION: true

        steps:
        - uses: actions/checkout@v2

        - uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 0.13.2

        - name: Install TFLint
          run: source <(curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh)

        - name: Running TFLint
          run: |
              terraform init -backend=false
              echo "Running TFLint in $(pwd)"
              tflint --module
              echo "TFLint has finished inspecting files in $(pwd)"

    tfsec:
        name: Running tfsec
        runs-on: ubuntu-latest
        env:
            TF_IN_AUTOMATION: true

        steps:
        - uses: triat/terraform-security-scan@v1
